# -*- coding: utf-8 -*-
"""project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vgbdIGjkzC95nPwfrE308rveknQy5eNR
"""

!pip install vaderSentiment

import nltk # Natural Language Toolkit
import pandas as pd # is a software library
import string
import matplotlib.pyplot as plt
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

messages = [line.rstrip() for line in open("/content/Tweets.csv")]
analyser = SentimentIntensityAnalyzer()
summary = {"positive":0,"neutral":0,"negative":0}
for x in messages:
  score = analyser.polarity_scores(x)
  if(score["compound"]==0.0):
    summary["neutral"] +=1
    neutral=summary["neutral"] 
  elif score["compound"] > 0.0:
    summary["positive"] +=1
    positive=summary["positive"] 
  else:
    summary["negative"] +=1
    negative=summary["negative"]
  print(x)
  print("Overall sentiment dictionary is : ", score) 
  print("sentence was rated as ", score['neg']*100, "% Negative") 
  print("sentence was rated as ", score['neu']*100, "% Neutral") 
  print("sentence was rated as ", score['pos']*100, "% Positive") 
  print("Sentence Overall Rated As", end = " ") 
  #decide message sentiment as positive, negative or neutral 
  if score['compound'] >= 0.05 : print("Positive") 
  elif score['compound'] <= - 0.05 : print("Negative") 
  else : print("Neutral") 
  print('\n')
#overall result
print(summary)

















